"use client";
import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { fixtures, teams, teamLogos, standings, mainSponsors, awardSponsors } from './data';
import { watchHuntersSquad, watchLiveMatch } from './firebaseData';

const Arrow = () => <span className="arrow" aria-hidden="true">↗</span>;
const Btn = ({ href, children, ghost = false }) => <Link className={`btn ${ghost ? 'btn-ghost' : ''}`} href={href}>{children}<Arrow /></Link>;
function Mark({ small = false }) { return <div className={`mark ${small ? 'mark-small' : ''}`}><img src="/assets/huntersFc/huntersFcLogo.png" alt="Hunters FC crest" /></div> }
function Header() {
    const [open, setOpen] = useState(false); return <>
        <header className="header"><Link className="brand" href="/"><Mark small /><span>HUNTERS FC<small>NIRANNAPARAMBU</small></span></Link><div className="header-actions"><nav className="header-links" aria-label="Primary navigation"><Link href="/npl">NPL</Link><Link href="/#team">Squad</Link><Link href="/#location">Map</Link></nav><button className={`menu-btn ${open ? 'open' : ''}`} onClick={() => setOpen(!open)} aria-label="Open menu"><i /><i /></button></div></header>
        <div className={`menu ${open ? 'show' : ''}`}><div className="menu-links">{[['/', 'Home'], ['/npl', 'NPL Season 4'], ['/#team', 'Team squad'], ['/#location', 'Club map'], ['/admin', 'Admin preview']].map(([to, label], i) => <Link style={{ '--i': i }} onClick={() => setOpen(false)} key={label} href={to}>{label}<span>0{i + 1}</span></Link>)}</div><div className="menu-foot">Nirannaparambu · Kerala · 679328</div></div>
    </>
}
function Reveal({ children, className = '' }) { return <div className={`reveal ${className}`}>{children}</div> }
function Eyebrow({ children, dark = false }) { return <div className={`eyebrow ${dark ? 'eyebrow-dark' : ''}`}><i /> {children}</div> }
const huntersFormation = [
    { name: 'Shamveel', role: 'Goal Keeper', pos: 'gk' },
    { name: 'Salman', role: 'Center Back', pos: 'cb' },
    { name: 'Anas', role: 'Right Back', pos: 'rb' },
    { name: 'Fasil', role: 'Left Back', pos: 'lb' },
    { name: 'Sreekuttan', role: 'Center Forward', pos: 'cf' },
    { name: 'Dilshad', role: 'Left Forward', pos: 'rw' },
    { name: 'Ajmal', role: 'Right Forward', pos: 'rf' }
];
export function Home() {
    return <main>
        <section id="top" className="hero"><div className="hero-image" /><div className="hero-shade" /><img className="hero-crest" src="/assets/huntersFc/huntersFcLogo.png" alt="" /><div className="hero-copy"><Eyebrow>Hunters FC · NPB</Eyebrow><h1>MORE THAN<br /><em>FOOTBALL.</em></h1><p>A club built around passion, brotherhood and the community that made us.</p><div className="button-row"><Btn href="#team">Discover the club</Btn><Btn href="/npl" ghost>NPL Season 4</Btn></div></div><div className="hero-index"><span>EST.</span><b>NPB</b><span>KERALA</span></div><a className="scroll-cue" href="#npl-spotlight"><i /><span>SCROLL TO DISCOVER</span></a></section>
        <div className="club-marquee" aria-label="Football, community, brotherhood and purpose"><div><span>FOOTBALL</span><i>✦</i><span>COMMUNITY</span><i>✦</i><span>BROTHERHOOD</span><i>✦</i><span>PURPOSE</span><i>✦</i><span>FOOTBALL</span><i>✦</i><span>COMMUNITY</span><i>✦</i></div></div>
        <section id="npl-spotlight" className="npl-tease section"><div className="npl-card"><div className="npl-top"><Eyebrow>NPL · Season 04</Eyebrow><span className="pulse"><i /> HAPPENING TODAY</span></div><div className="npl-title"><img src="/assets/npl/nplLogo.png" alt="NPL Season 4 logo" /><div><strong>NPL</strong><span>04</span></div></div><div className="event-meta"><div><small>Saturday</small><b>08 AUG 2026</b></div><div><small>Kick off</small><b>7:00 PM</b></div><div><small>Venue</small><b>THRILLOX TURF</b></div></div><Btn href="/npl">Enter tournament</Btn></div></section>
        <section id="team" className="paper section team"><Reveal><div className="eyebrow squad-label"><i /> Team Squad</div><div className="section-head"><h2>THE<br /><em>HUNTERS.</em></h2><span className="big-no">7S</span></div><FormationPitch /></Reveal></section>
        <section id="location" className="paper section location"><div className="location-backdrop" aria-hidden="true">NPB</div><div className="location-layout"><div className="location-copy"><Eyebrow dark>Home ground</Eyebrow><h2>FROM NPB.<br /><em>FOR NPB.</em></h2><p className="location-lead">This is where the Hunters belong our football home in the heart of Nirannaparambu.</p><a className="btn dark-btn location-directions" href="https://maps.app.goo.gl/EVdD9biwy6PmWjAs6" target="_blank" rel="noreferrer">Get directions <Arrow /></a></div><div className="map-shell"><div className="map-label"><div><span><i /> HUNTERS FC HOME</span><b>11.156666° N · 76.215632° E</b></div><strong>NPB <em>679328</em></strong></div><div className="map-frame"><iframe title="Hunters FC satellite map" loading="lazy" src="https://maps.google.com/maps?q=11.156666,76.215632&amp;t=k&amp;z=17&amp;output=embed" /><div className="map-club-pin"><img src="/assets/huntersFc/huntersFcLogo.png" alt="" /><span><small>YOU'VE FOUND US</small><b>HUNTERS FC</b></span></div><a className="map-open" href="https://maps.app.goo.gl/EVdD9biwy6PmWjAs6" target="_blank" rel="noreferrer" aria-label="Open Hunters FC in Google Maps">↗</a></div><footer><span>SATELLITE MAP PREVIEW</span><b>WELCOME TO OUR HOME.</b></footer></div></div></section>
        <Footer /><ClubBottomNav />
    </main>
}
function FormationPitch() { const [remote, setRemote] = useState(null); useEffect(() => watchHuntersSquad(data => data?.players?.length && setRemote(data.players), () => { }), []); const roleClass = { 'Goal Keeper': 'gk', 'Left Back': 'lb', 'Center Back': 'cb', 'Right Back': 'rb', 'Left Forward': 'rw', 'Center Forward': 'cf', 'Right Forward': 'rf' }; const source = remote || huntersFormation; const starters = source.filter(p => (p.status || 'active') !== 'substitute' && p.position !== 'Substitute').slice(0, 7).map(p => ({ ...p, role: p.role || p.position, pos: p.pos || roleClass[p.position] || 'cf' })); const subs = source.filter(p => p.status === 'substitute' || p.position === 'Substitute'); const shownSubs = subs.length ? subs : [{ name: 'Sabith', number: 8 }, { name: 'Shamil', number: 9 }, { name: 'Monas', number: 10 }]; return <div className="formation-shell"><div className="formation-stage"><div className="football-pitch"><div className="pitch-lines"><i className="half-line" /><i className="center-circle" /><i className="box box-top" /><i className="box box-bottom" /><i className="goal goal-top" /><i className="goal goal-bottom" /></div>{starters.map((p, i) => <div className={`player-marker ${p.pos}`} key={p.id || p.name}><span>{p.number || i + 1}</span><div><b>{p.name}</b><small>{p.role}</small></div></div>)}</div><aside className="sideline-subs" aria-label="Substitutes"><small>SUBS</small>{shownSubs.slice(0, 4).map((p, i) => <span key={p.id || p.name}><i>{String(p.number || i + 8).padStart(2, '0')}</i><b>{p.name}</b></span>)}</aside></div></div> }
function Footer() { return <footer className="site-footer"><div className="footer-panel"><div className="footer-columns"><div><span className="footer-pill">More than a club</span><h3>FOOTBALL.<br />COMMUNITY.<br />BROTHERHOOD.</h3></div><div><span className="footer-pill">Our home</span><h3>NIRANNAPARAMBU<br />KERALA · 679328</h3><a href="https://maps.app.goo.gl/EVdD9biwy6PmWjAs6" target="_blank" rel="noreferrer">Open Google Maps ↗</a></div><nav><span className="footer-pill">Explore</span><Link href="/#team">Team Squad</Link><Link href="/#location">Club Map</Link><Link href="/npl">NPL Season 4</Link><Link href="/admin">Admin preview</Link></nav></div><div className="footer-art"><div className="footer-sticker sticker-npb">NPB</div><div className="footer-sticker sticker-ball">⚽</div><div className="footer-sticker sticker-year">2026</div><div className="footer-logo-sticker"><Mark /></div><strong>HUNTERS</strong></div><div className="footer-meta"><small>© 2026 HUNTERS FC NPB</small><b>MORE THAN FOOTBALL.</b></div></div></footer> }
function ClubNavIcon({ name }) { const paths = { home: <><path d="M3 10.5 12 3l9 7.5" /><path d="M5.5 9.5V21h13V9.5M9 21v-7h6v7" /></>, squad: <><circle cx="9" cy="8" r="3" /><circle cx="17" cy="9" r="2.5" /><path d="M3.5 20c.4-4 2.2-6 5.5-6s5.1 2 5.5 6M14 15c3.8-.7 6 1.1 6.5 4.5" /></>, join: <><path d="M12 21s-7-4.4-7-10a4 4 0 0 1 7-2.7A4 4 0 0 1 19 11c0 5.6-7 10-7 10Z" /><path d="M12 7v8M8 11h8" /></>, npl: <><circle cx="12" cy="12" r="9" /><path d="m12 7 3 2.2-1.1 3.5h-3.8L9 9.2 12 7ZM6 10l3 1M18 10l-3 1M8 18l2.5-5.3M16 18l-2.5-5.3" /></>, top: <><path d="m5 11 7-7 7 7M12 4v17" /></> }; return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg> }
function ClubBottomNav() { return <nav className="club-bottom-nav" aria-label="Mobile club navigation"><a className="active" href="#top"><i><ClubNavIcon name="home" /></i><span>Home</span></a><a href="#team"><i><ClubNavIcon name="squad" /></i><span>Squad</span></a><a href="#location"><i><ClubNavIcon name="join" /></i><span>Map</span></a><Link href="/npl"><i><ClubNavIcon name="npl" /></i><span>NPL</span></Link><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><i><ClubNavIcon name="top" /></i><span>Top</span></button></nav> }

export function Npl() {
    const [liveMatch, setLiveMatch] = useState(null); useEffect(() => watchLiveMatch(setLiveMatch, () => { }), []); const publicMatch = liveMatch || { homeTeam: "Avengers FC", awayTeam: "Atletico FC", homeScore: 0, awayScore: 0, status: "UP NEXT", minute: 0 }; const homeIndex = Math.max(0, teams.indexOf(publicMatch.homeTeam)); const awayIndex = Math.max(0, teams.indexOf(publicMatch.awayTeam)); return <main className="npl-page"><section className="npl-hero"><div className="npl-grid" /><div className="npl-crest-wall" aria-hidden="true">{teamLogos.map((logo, i) => <img src={logo} alt="" key={logo} style={{ '--crest': i }} />)}</div><img className="npl-official-logo" src="/assets/npl/nplLogo.png" alt="Nirannaparambu Premier League Season 4" /><div className="npl-hero-copy"><Eyebrow>Nirannaparambu Premier League</Eyebrow><div className="live-pill"><i /> HAPPENING TODAY</div><h1>NPL<span>04</span></h1><p>Eight teams. One night. One champion.</p><div className="event-line"><b>08 AUG 2026</b><span>7:00 PM ONWARDS</span><span>THRILLOX FOOTBALL TURF · WANDOOR</span></div><div className="npl-hero-actions"><a href="#fixtures">Explore fixtures <Arrow /></a><a href="#teams">Meet the teams <Arrow /></a></div><img className="npl-type-art" src="/assets/npl/nplTyphography.png" alt="NPL Season 4 Malayalam typography" /></div></section>
        <div className="npl-marquee" aria-label="NPL Season 4 teams"><div>{teams.concat(teams).map((team, i) => <React.Fragment key={`${team}-${i}`}><span>{team}</span><i>✦</i></React.Fragment>)}</div></div>
        <NplNav /><section className="npl-content section"><div className="tournament-numbers"><article><small>TEAMS</small><b>08</b><span>One trophy</span></article><article><small>MATCHES</small><b>15</b><span>One night</span></article><article><small>SEASON</small><b>04</b><span>The legacy grows</span></article></div><div className={`match-feature ${publicMatch.status === 'LIVE' ? 'is-live' : ''}`}><div className="match-glow" /><div className="match-label"><span>{publicMatch.status}</span><small>{publicMatch.status === 'LIVE' ? `${publicMatch.minute || 0}' · LIVE FROM WANDOOR` : 'GROUP A · MATCH 01'}</small></div><div className="score"><div><TeamBadge n={homeIndex} /><b>{publicMatch.homeTeam}</b></div><strong><small>{publicMatch.status === 'LIVE' ? `${publicMatch.minute || 0}'` : '7:00'}</small>{['LIVE', 'HALF TIME', 'FULL TIME'].includes(publicMatch.status) ? `${publicMatch.homeScore} — ${publicMatch.awayScore}` : 'VS'}</strong><div><TeamBadge n={awayIndex} /><b>{publicMatch.awayTeam}</b></div></div><button>Match centre <Arrow /></button></div>
            <Block id="fixtures" title="TODAY'S FIXTURES" aside="3 MATCHES"><div className="fixture-scroll">{fixtures.map((f, i) => <Fixture f={f} key={i} />)}</div></Block>
            <Block id="standings" title="GROUP A" aside="STANDINGS"><div className="table"><div className="tr th"><span># TEAM</span><span>P</span><span>GD</span><span>PTS</span></div>{standings.map((r, i) => <div className="tr" key={r[0]}><span><b>{i + 1}</b><TeamBadge n={i} />{r[0]}</span><span>{r[1]}</span><span>0</span><strong>{r[2]}</strong></div>)}</div></Block>
            <Block id="teams" title="THE EIGHT" aside="TEAMS"><div className="team-scroll">{teams.map((t, i) => <article key={t}><TeamBadge n={i} /><small>TEAM 0{i + 1}</small><h3>{t}</h3><span>View squad ↗</span></article>)}</div></Block>
            <Block id="knockout" title="ROAD TO THE FINAL" aside="KNOCKOUT"><div className="bracket"><div><small>QUARTER FINALS</small><b>8 TEAMS</b></div><i>→</i><div><small>SEMI FINALS</small><b>4 TEAMS</b></div><i>→</i><div><small>FINAL</small><b>2 TEAMS</b></div><i>→</i><div className="champ"><small>CHAMPION</small><b>01</b></div></div></Block>
            <SponsorShowcase />
        </section><Footer /><div className="bottom-nav"><a href="#">Today</a><a href="#fixtures">Fixtures</a><a href="#standings">Table</a><a href="#teams">Teams</a><a href="#knockout">More</a></div></main>
}
function NplNav() { return <nav className="npl-nav"><a href="#">Overview</a><a href="#fixtures">Fixtures</a><a href="#standings">Standings</a><a href="#teams">Teams</a></nav> }
function TeamBadge({ n = 0 }) { return <span className="team-badge"><img src={teamLogos[n]} alt={`${teams[n]} logo`} /></span> }
function Fixture({ f }) { return <article className="fixture"><div><span>{f.status}</span><small>{f.round}</small></div><div className="fixture-teams"><p><TeamBadge n={teams.indexOf(f.home)} />{f.home}<b>{f.hs}</b></p><p><TeamBadge n={teams.indexOf(f.away)} />{f.away}<b>{f.as}</b></p></div><footer><b>{f.time}</b><span>Match centre ↗</span></footer></article> }
function Block({ id, title, aside, children }) { return <section className="npl-block" id={id || title.toLowerCase().replaceAll(' ', '-')}><div className="block-title"><h2>{title}</h2><span>{aside}</span></div>{children}</section> }
function SponsorShowcase() { return <Block title="BACKED BY" aside="OFFICIAL SPONSORS"><div className="sponsor-lead">{mainSponsors.map(s => <article key={s.title}><small>{s.title}</small><img src={s.image} alt={s.title} /></article>)}</div><div className="award-title"><span>INDIVIDUAL AWARD SPONSORS</span><i /></div><div className="sponsor-awards">{awardSponsors.map(s => <article key={s.title}><small>{s.title}</small><img src={s.image} alt={s.title} /></article>)}</div></Block> }

export function Admin() { const [section, setSection] = useState('Overview'); return <main className="admin"><aside><Link href="/" className="admin-brand"><Mark small /><b>HUNTERS<br />CONTROL</b></Link>{['Overview', 'Matches', 'Fixtures', 'Teams', 'Players', 'Club', 'Committee', 'Members', 'Community', 'Gallery', 'Sponsors', 'Settings'].map(x => <button className={section === x ? 'active' : ''} onClick={() => setSection(x)} key={x}><i />{x}</button>)}<div className="admin-user"><span>AD</span><div><b>Administrator</b><small>Demo mode</small></div></div></aside><section className="admin-main"><header><div><small>ADMIN PANEL / {section.toUpperCase()}</small><h1>{section}</h1></div><Link href="/">View website ↗</Link></header><div className="demo-note"><b>FRONTEND PREVIEW</b><span>Changes are stored as demo data until Firebase is connected.</span></div>{section === 'Overview' ? <AdminOverview /> : <AdminList title={section} />}</section><nav className="admin-mobile">{['Overview', 'Matches', 'Teams', 'Club', 'Settings'].map(x => <button onClick={() => setSection(x)} className={section === x ? 'active' : ''} key={x}><i />{x}</button>)}</nav></main> }
function AdminOverview() { return <><div className="admin-stats"><article><small>NPL STATUS</small><b>HAPPENING<br />TODAY</b><span className="status-dot">● Live-day mode</span></article><article><small>TEAMS</small><b className="num">08</b><span>All squads editable</span></article><article><small>FIXTURES</small><b className="num">15</b><span>3 scheduled today</span></article><article><small>CLUB CONTENT</small><b>12<span>/18</span></b><span>Sections completed</span></article></div><div className="admin-columns"><section><div className="admin-title"><h2>Match control</h2><button>All matches</button></div>{fixtures.slice(0, 2).map((f, i) => <div className="control-match" key={i}><span>{f.time}</span><div><b>{f.home}</b><small>vs</small><b>{f.away}</b></div><button>OPEN</button></div>)}</section><section><div className="admin-title"><h2>Quick actions</h2></div>{['Add club member', 'Create fixture', 'Upload gallery', 'New community story'].map(x => <button className="quick" key={x}>{x}<Arrow /></button>)}</section></div></> }
function AdminList({ title }) { return <section className="admin-list"><div className="admin-title"><div><h2>Manage {title.toLowerCase()}</h2><p>Content shown here is structured for the future Firebase collection.</p></div><button>+ Add new</button></div>{[1, 2, 3, 4].map((x) => <div className="list-row" key={x}><span>{String(x).padStart(2, '0')}</span><div><b>{title} demo entry {x}</b><small>Placeholder content · Updated today</small></div><i>•••</i></div>)}</section> }
function ScrollTop() { const pathname = usePathname(); useEffect(() => { window.scrollTo(0, 0) }, [pathname]); useEffect(() => { const ob = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && e.target.classList.add('seen')), { threshold: .08 }); document.querySelectorAll('.reveal').forEach(x => ob.observe(x)); return () => { ob.disconnect() } }, [pathname]); return null }
export function ClubPage() { return <><ScrollTop /><Header /><Home /></> }
export function NplPage() { return <><ScrollTop /><Header /><Npl /></> }
